on:
  push:
    branches:
      - master






jops:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Before' 
        run: ls

      - users: actions/checkout@v3

      - name: 'After' 
        run: ls